\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={COVID Aerosols - Merged Data Codebook},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=2cm]{geometry}
\usepackage{longtable,booktabs}
% Fix footnotes in tables (requires footnote package)
\IfFileExists{footnote.sty}{\usepackage{footnote}\makesavenoteenv{longtable}}{}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\newcommand{\fullline}{\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}}
\renewcommand\familydefault{\sfdefault}
\newcommand{\bminione}{\begin{minipage}{0.75 \textwidth}}
\newcommand{\bminitwo}{\begin{minipage}{0.25 \textwidth}}
\newcommand{\emini}{\end{minipage}}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother

\title{COVID Aerosols - Merged Data Codebook}
\providecommand{\subtitle}[1]{}
\subtitle{Autogenerated data summary from dataMaid}
\author{}
\date{\vspace{-2.5em}2021-01-06 09:42:40}

\begin{document}
\maketitle

\hypertarget{data-report-overview}{%
\section{Data report overview}\label{data-report-overview}}

The dataset examined has the following dimensions:

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.33\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.33\columnwidth}\raggedright
Number of observations\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
55\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.33\columnwidth}\raggedright
Number of variables\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
86\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{codebook-summary-table}{%
\section{Codebook summary table}\label{codebook-summary-table}}

\begin{longtable}[]{@{}lllrcl@{}}
\toprule
\begin{minipage}[b]{0.20\columnwidth}\raggedright
Label\strut
\end{minipage} & \begin{minipage}[b]{0.23\columnwidth}\raggedright
Variable\strut
\end{minipage} & \begin{minipage}[b]{0.10\columnwidth}\raggedright
Class\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\raggedleft
\# unique values\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\centering
Missing\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedright
Description\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Sample ID\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{sampleid}{sampleid}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
55\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Date of collection\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{colldate}{colldate}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
21\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Outdoor CO2 level on date of collection (ppm)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{outdoorco2}{outdoorco2}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
15\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Hospital name\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{hosp}{hosp}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
7\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Sampling location\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{samploc}{samploc}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
10\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Type of sampling space\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{loctype}{loctype}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
6\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Start time\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{starttime}{starttime}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
36\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Ambient temperature at start (C)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{tempstart}{tempstart}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
42\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Ambient humidity at start\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{humiditystart}{humiditystart}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
53\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
CO2 level at start of collection (ppm)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2start}{co2start}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
53\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of COVID patients\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numcovidstart}{numcovidstart}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
18\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of non-COVID patients\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numnoncovidstart}{numnoncovidstart}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
5\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of staff\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numstaffstart}{numstaffstart}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
9\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of people other than patients or staff (visitors, etc.)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numotherstart}{numotherstart}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
20\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of people wearing masks\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{nummasksstart}{nummasksstart}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
3\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
96.36 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
People\_start\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numpeoplestart}{numpeoplestart}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
31\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of patients using nasal cannula\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numnasal}{numnasal}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
5\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of patients using oxygen masks\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numoxymask}{numoxymask}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
9\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of patients using CPAP (non-invasive ventilation)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numcpap}{numcpap}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of patients intubated\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numintub}{numintub}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
3\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Distance of air sampler from nearest patient (feet, convert inches to
decimal)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{distpatient}{distpatient}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
41\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Distance of air sampler from nearest window (feet, convert inches to
decimal)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{distwindow}{distwindow}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
40\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Is the nearest window open or closed?\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{nearwindowopen}{nearwindowopen}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
3\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Distance of air sampler from nearest door (feet, convert inches to
decimal)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{distdoor}{distdoor}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
52\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Is the nearest door open or closed?\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{neardooropen}{neardooropen}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of COVID patients (15 minutes)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numcovidmid}{numcovidmid}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
20\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
5.45 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of non-COVID patients (15 minutes)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numnoncovidmid}{numnoncovidmid}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
5\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
3.64 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of staff (15 minutes)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numstaffmid}{numstaffmid}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
8\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
3.64 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of people other than patients or staff (15 minutes)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numothermid}{numothermid}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
21\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
3.64 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
People\_midpoint\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numpeoplemid}{numpeoplemid}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
26\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
5.45 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of windows fully open\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numwinfullopen}{numwinfullopen}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
6\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
3.64 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of windows partially open\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numwinpartopen}{numwinpartopen}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
8\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of windows closed\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numwinclosed}{numwinclosed}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
11\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numwinopen}{numwinopen}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
9\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
3.64 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numwintotal}{numwintotal}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
15\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
3.64 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of doors fully open (doors leading to external corridor or
separate room,\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numdoorfullopen}{numdoorfullopen}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
5\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of doors partially open (doors leading to external corridor or
separate r\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numdoorpartopen}{numdoorpartopen}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
4\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of doors closed (doors leading to external corridor or separate
room, not\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numdoorclosed}{numdoorclosed}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
7\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numdoortotal}{numdoortotal}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
10\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numdooropen}{numdooropen}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
6\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Total number of fans\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{totfan}{totfan}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
19\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of fans in operation\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numfanon}{numfanon}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
15\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
40.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of air conditioning units in operation\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numacon}{numacon}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
6\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Room width (feet, convert inches to decimal)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{roomwidth}{roomwidth}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
39\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
23.64 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Room length (feet, convert inches to decimal)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{roomlength}{roomlength}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
40\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
23.64 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Room height (feet, convert inches to decimal)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{roomheight}{roomheight}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
29\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Room area (ft cub)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{roomarea}{roomarea}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
38\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
32.73 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
End time\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{endtime}{endtime}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
32\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Ambient temperature at end (C)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{tempend}{tempend}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
48\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
CO2 level at end of collection (ppm)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2end}{co2end}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
54\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Ambient humidity at end\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{humidityend}{humidityend}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
41\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of COVID patients (endpoint)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numcovidend}{numcovidend}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
20\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of non-COVID patients (endpoint)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numnoncovidend}{numnoncovidend}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
7\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of staff (endpoint)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numstaffend}{numstaffend}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
8\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Number of people other than patients or staff (endpoint)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{numotherend}{numotherend}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
22\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
People\_end\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{peopleend}{peopleend}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
31\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
CO2 level at 5 minutes (ppm)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2_5min}{co2\_5min}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
53\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
3.64 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
CO2 level at 10 minutes (ppm)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2_10min}{co2\_10min}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
51\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
5.45 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
CO2 level at 15 minutes (ppm)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2_15min}{co2\_15min}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
50\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
5.45 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
CO2 level at 20 minutes (ppm)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2_20min}{co2\_20min}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
52\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
7.27 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
CO2 level at 25 minutes (ppm)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2_25min}{co2\_25min}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
52\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
5.45 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Notes:\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{notes}{notes}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
49\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
12.73 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{id}{\_id}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
55\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{submittime}{submittime}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
51\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{fixco2}{fixco2}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
5\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2startnew}{co2startnew}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
54\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2_5minnew}{co2\_5minnew}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
51\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
3.64 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2_10minnew}{co2\_10minnew}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
51\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
5.45 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2_15minnew}{co2\_15minnew}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
49\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
5.45 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2_20minnew}{co2\_20minnew}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
52\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
7.27 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2_25minnew}{co2\_25minnew}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
52\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
5.45 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2endnew}{co2endnew}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
55\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
1.82 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{co2average}{co2average}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
55\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Wash location\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{washlocation}{washlocation}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
3\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Sample type (Test/neg control)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{sampletype}{sampletype}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Collection site\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{collectionsite}{collectionsite}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
5\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Room type\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{roomtype}{roomtype}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
14\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
SARS-CoV-2 (Detected/undetected)\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{result}{result}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
3\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
N1-Ct value\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{n1ctvalue}{n1ctvalue}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
16\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
N1-quantity/reaction\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{n1quantityreaction}{n1quantityreaction}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
17\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
70.91 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
N1-quantity/sampleX10\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{n1quantitysamplex10}{n1quantitysamplex10}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
17\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
70.91 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Batch number\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{batchnumber}{batchnumber}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
12\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Collection date\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{collectiondate}{collectiondate}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
14\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
RNA extraction Date\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{rnadate}{rnadate}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
100.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.20\columnwidth}\raggedright
Comments:\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedright
\textbf{\protect\hyperlink{comments}{comments}}\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedright
character\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedright
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{variable-list}{%
\section{Variable list}\label{variable-list}}

\hypertarget{sampleid}{%
\subsection{sampleid}\label{sampleid}}

\emph{Sample ID}

\begin{itemize}
\tightlist
\item
  The variable is a key (distinct values for each observation).
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{colldate}{%
\subsection{colldate}\label{colldate}}

\emph{Date of collection}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
21\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
``2020-12-06''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-2-colldate-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "2020-10-07", "2020-10-12", "2020-10-14",
  "2020-10-18", "2020-10-21", "2020-10-28", "2020-11-08", "2020-11-10",
  "2020-11-15", "2020-11-17", "2020-11-23", "2020-11-25", "2020-11-30",
  "2020-12-06", "2020-12-07", "2020-12-08", "2020-12-13", "2020-12-20",
  "2020-12-22", "2020-12-27", "2020-12-29".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{outdoorco2}{%
\subsection{outdoorco2}\label{outdoorco2}}

\emph{Outdoor CO2 level on date of collection (ppm)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
15\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
406\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
399.5; 410\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
388; 556\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-3-outdoorco2-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{hosp}{%
\subsection{hosp}\label{hosp}}

\emph{Hospital name}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.51\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.51\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.51\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.51\columnwidth}\raggedleft
7\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.51\columnwidth}\raggedleft
``Dhaka Medical College and Hospital''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-4-hosp-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "Dhaka Medical College and Hospital", "icddr,b
  Hospital", "Kurmitola General Hospital", "Mugda Medical College and
  Hospital", "Shaheed Suhrawardy Medical College and Hospital", "Sheikh
  Rasel National Gastroliver Institute", "Square Hospital".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{samploc}{%
\subsection{samploc}\label{samploc}}

\emph{Sampling location}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.30\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
10\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
``COVID general ward''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-5-samploc-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "Cardiology OPD", "COVID cabin", "COVID
  general ward", "COVID Hallway", "COVID ICU", "COVID isolation ward",
  "Non-COVID general ward", "OPD", "Sample collection booth", "Triage".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{loctype}{%
\subsection{loctype}\label{loctype}}

\emph{Type of sampling space}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
6\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
``Open ward''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-6-loctype-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "Bathroom", "Cabin", "Doctor's cabin", "Open
  ward", "Partitioned booth", "Waiting area".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{starttime}{%
\subsection{starttime}\label{starttime}}

\emph{Start time}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.30\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
36\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
``13:00:00.000+06:00''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-7-starttime-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "11:30:00.000+06:00", "11:34:00.000+06:00",
  "11:40:00.000+06:00", "11:58:00.000+06:00", "12:00:00.000+06:00",
  "12:16:00.000+06:00", "12:17:00.000+06:00", "12:18:00.000+06:00",
  "12:21:00.000+06:00", "12:24:00.000+06:00", "12:27:00.000+06:00",
  "12:30:00.000+06:00", "12:36:00.000+06:00", "12:47:00.000+06:00",
  "12:51:00.000+06:00", "12:53:00.000+06:00", "13:00:00.000+06:00",
  "13:04:00.000+06:00", "13:15:00.000+06:00", "13:20:00.000+06:00",
  "13:22:00.000+06:00", "13:25:00.000+06:00", "13:27:00.000+06:00",
  "13:28:00.000+06:00", "13:33:00.000+06:00", "13:35:00.000+06:00",
  "13:41:00.000+06:00", "13:50:00.000+06:00", "13:55:00.000+06:00",
  "14:00:00.000+06:00", "14:03:00.000+06:00", "14:04:00.000+06:00",
  "14:17:00.000+06:00", "14:44:00.000+06:00", "15:00:00.000+06:00",
  "15:10:00.000+06:00".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{tempstart}{%
\subsection{tempstart}\label{tempstart}}

\emph{Ambient temperature at start (C)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
42\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
27\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
25.15; 29.05\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
22.5; 31.8\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-8-tempstart-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{humiditystart}{%
\subsection{humiditystart}\label{humiditystart}}

\emph{Ambient humidity at start}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
53\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
63.3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
58.8; 71.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
51.5; 83.8\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-9-humiditystart-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2start}{%
\subsection{co2start}\label{co2start}}

\emph{CO2 level at start of collection (ppm)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
53\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
770\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
566.5; 928.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
426; 1731\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-10-co2start-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numcovidstart}{%
\subsection{numcovidstart}\label{numcovidstart}}

\emph{Number of COVID patients}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
18\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
1; 6.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 62\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-11-numcovidstart-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numnoncovidstart}{%
\subsection{numnoncovidstart}\label{numnoncovidstart}}

\emph{Number of non-COVID patients}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 40\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-12-numnoncovidstart-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numstaffstart}{%
\subsection{numstaffstart}\label{numstaffstart}}

\emph{Number of staff}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
8\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 17\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-13-numstaffstart-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numotherstart}{%
\subsection{numotherstart}\label{numotherstart}}

\emph{Number of people other than patients or staff (visitors, etc.)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
20\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
2; 13\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 71\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-14-numotherstart-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{nummasksstart}{%
\subsection{nummasksstart}\label{nummasksstart}}

\emph{Number of people wearing masks}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
53 (96.36 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
29\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
18.5; 39.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
8; 50\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-15-nummasksstart-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numpeoplestart}{%
\subsection{numpeoplestart}\label{numpeoplestart}}

\emph{People\_start}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
30\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
9.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
4; 25.75\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 104\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-16-numpeoplestart-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numnasal}{%
\subsection{numnasal}\label{numnasal}}

\emph{Number of patients using nasal cannula}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
4\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 5\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-17-numnasal-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numoxymask}{%
\subsection{numoxymask}\label{numoxymask}}

\emph{Number of patients using oxygen masks}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
8\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 11\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-18-numoxymask-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numcpap}{%
\subsection{numcpap}\label{numcpap}}

\emph{Number of patients using CPAP (non-invasive ventilation)}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "0". The variable
  contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numintub}{%
\subsection{numintub}\label{numintub}}

\emph{Number of patients intubated}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 2\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-20-numintub-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{distpatient}{%
\subsection{distpatient}\label{distpatient}}

\emph{Distance of air sampler from nearest patient (feet, convert inches
to decimal)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
41\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
6\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
4.34; 7.8\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
2; 999\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-21-distpatient-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{distwindow}{%
\subsection{distwindow}\label{distwindow}}

\emph{Distance of air sampler from nearest window (feet, convert inches
to decimal)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
40\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
15.92\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
11.71; 989.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0; 999\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-22-distwindow-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{nearwindowopen}{%
\subsection{nearwindowopen}\label{nearwindowopen}}

\emph{Is the nearest window open or closed?}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
``Closed''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-23-nearwindowopen-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "Closed", "N/A", "Open".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{distdoor}{%
\subsection{distdoor}\label{distdoor}}

\emph{Distance of air sampler from nearest door (feet, convert inches to
decimal)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
51\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
15.05\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
11.58; 21.38\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0; 68.5\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-24-distdoor-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{neardooropen}{%
\subsection{neardooropen}\label{neardooropen}}

\emph{Is the nearest door open or closed?}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
``Open''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-25-neardooropen-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "Closed", "Open".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numcovidmid}{%
\subsection{numcovidmid}\label{numcovidmid}}

\emph{Number of COVID patients (15 minutes)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
3 (5.45 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
19\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1; 7\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 62\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-26-numcovidmid-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numnoncovidmid}{%
\subsection{numnoncovidmid}\label{numnoncovidmid}}

\emph{Number of non-COVID patients (15 minutes)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
2 (3.64 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
4\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 13\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-27-numnoncovidmid-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numstaffmid}{%
\subsection{numstaffmid}\label{numstaffmid}}

\emph{Number of staff (15 minutes)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
2 (3.64 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
7\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 12\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-28-numstaffmid-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numothermid}{%
\subsection{numothermid}\label{numothermid}}

\emph{Number of people other than patients or staff (15 minutes)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
2 (3.64 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
20\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1; 9\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 41\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-29-numothermid-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numpeoplemid}{%
\subsection{numpeoplemid}\label{numpeoplemid}}

\emph{People\_midpoint}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
3 (5.45 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
25\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
8\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
2.75; 19\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 104\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-30-numpeoplemid-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numwinfullopen}{%
\subsection{numwinfullopen}\label{numwinfullopen}}

\emph{Number of windows fully open}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
2 (3.64 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 11\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-31-numwinfullopen-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numwinpartopen}{%
\subsection{numwinpartopen}\label{numwinpartopen}}

\emph{Number of windows partially open}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
8\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 8\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-32-numwinpartopen-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numwinclosed}{%
\subsection{numwinclosed}\label{numwinclosed}}

\emph{Number of windows closed}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
11\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 3.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 20\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-33-numwinclosed-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numwinopen}{%
\subsection{numwinopen}\label{numwinopen}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
2 (3.64 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
8\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 19\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-34-numwinopen-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numwintotal}{%
\subsection{numwintotal}\label{numwintotal}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
2 (3.64 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
14\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 6\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 34\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-35-numwintotal-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numdoorfullopen}{%
\subsection{numdoorfullopen}\label{numdoorfullopen}}

\emph{Number of doors fully open (doors leading to external corridor or
separate room,}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
1; 1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 4\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-36-numdoorfullopen-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numdoorpartopen}{%
\subsection{numdoorpartopen}\label{numdoorpartopen}}

\emph{Number of doors partially open (doors leading to external corridor
or separate r}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
4\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 4\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-37-numdoorpartopen-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numdoorclosed}{%
\subsection{numdoorclosed}\label{numdoorclosed}}

\emph{Number of doors closed (doors leading to external corridor or
separate room, not}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
7\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 82\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-38-numdoorclosed-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numdoortotal}{%
\subsection{numdoortotal}\label{numdoortotal}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
10\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
1; 2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 85\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-39-numdoortotal-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numdooropen}{%
\subsection{numdooropen}\label{numdooropen}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
6\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
1; 2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 7\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-40-numdooropen-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{totfan}{%
\subsection{totfan}\label{totfan}}

\emph{Total number of fans}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
18\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 6.75\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 61\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-41-totfan-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numfanon}{%
\subsection{numfanon}\label{numfanon}}

\emph{Number of fans in operation}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
22 (40 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
14\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
0; 6\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
0; 49\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-42-numfanon-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numacon}{%
\subsection{numacon}\label{numacon}}

\emph{Number of air conditioning units in operation}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 4\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-43-numacon-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{roomwidth}{%
\subsection{roomwidth}\label{roomwidth}}

\emph{Room width (feet, convert inches to decimal)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
13 (23.64 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
38\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
20.24\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
14; 23.12\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
4.33; 88.92\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-44-roomwidth-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{roomlength}{%
\subsection{roomlength}\label{roomlength}}

\emph{Room length (feet, convert inches to decimal)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
13 (23.64 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
39\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
25.45\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
18.98; 43.13\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
6.5; 109\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-45-roomlength-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{roomheight}{%
\subsection{roomheight}\label{roomheight}}

\emph{Room height (feet, convert inches to decimal)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
29\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
10.33\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
8.53; 11.25\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
7.53; 14.25\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-46-roomheight-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{roomarea}{%
\subsection{roomarea}\label{roomarea}}

\emph{Room area (ft cub)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.26\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.26\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.26\columnwidth}\raggedleft
18 (32.73 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.26\columnwidth}\raggedleft
37\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.26\columnwidth}\raggedleft
4663.04\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.26\columnwidth}\raggedleft
2901.23; 11748.59\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.26\columnwidth}\raggedleft
288.49; 73852.51\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-47-roomarea-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{endtime}{%
\subsection{endtime}\label{endtime}}

\emph{End time}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.30\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
32\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
``13:30:00.000+06:00''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-48-endtime-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "", "12:00:00.000+06:00",
  "12:04:00.000+06:00", "12:10:00.000+06:00", "12:30:00.000+06:00",
  "12:46:00.000+06:00", "12:47:00.000+06:00", "12:51:00.000+06:00",
  "12:54:00.000+06:00", "12:57:00.000+06:00", "13:00:00.000+06:00",
  "13:06:00.000+06:00", "13:22:00.000+06:00", "13:23:00.000+06:00",
  "13:30:00.000+06:00", "13:34:00.000+06:00", "13:45:00.000+06:00",
  "13:50:00.000+06:00", "13:56:00.000+06:00", "13:58:00.000+06:00",
  "14:03:00.000+06:00", "14:05:00.000+06:00", "14:11:00.000+06:00",
  "14:20:00.000+06:00", "14:25:00.000+06:00", "14:30:00.000+06:00",
  "14:33:00.000+06:00", "14:34:00.000+06:00", "14:47:00.000+06:00",
  "15:14:00.000+06:00", "15:30:00.000+06:00", "15:46:00.000+06:00".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{tempend}{%
\subsection{tempend}\label{tempend}}

\emph{Ambient temperature at end (C)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
47\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
63.25\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
57.35; 70.75\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
50.1; 81.6\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-49-tempend-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2end}{%
\subsection{co2end}\label{co2end}}

\emph{CO2 level at end of collection (ppm)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
53\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
746.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
555; 885\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
404; 1604\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-50-co2end-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{humidityend}{%
\subsection{humidityend}\label{humidityend}}

\emph{Ambient humidity at end}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
40\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
25.9\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
24; 29.37\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
21.4; 32\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-51-humidityend-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numcovidend}{%
\subsection{numcovidend}\label{numcovidend}}

\emph{Number of COVID patients (endpoint)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
19\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1; 6.75\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 62\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-52-numcovidend-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numnoncovidend}{%
\subsection{numnoncovidend}\label{numnoncovidend}}

\emph{Number of non-COVID patients (endpoint)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
6\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 31\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-53-numnoncovidend-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numstaffend}{%
\subsection{numstaffend}\label{numstaffend}}

\emph{Number of staff (endpoint)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
7\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 1.75\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 11\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-54-numstaffend-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{numotherend}{%
\subsection{numotherend}\label{numotherend}}

\emph{Number of people other than patients or staff (endpoint)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
21\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 11.75\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 40\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-55-numotherend-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{peopleend}{%
\subsection{peopleend}\label{peopleend}}

\emph{People\_end}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
30\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
7.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
2.25; 22\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
0; 103\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-56-peopleend-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2_5min}{%
\subsection{co2\_5min}\label{co2_5min}}

\emph{CO2 level at 5 minutes (ppm)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
2 (3.64 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
52\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
710\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
570; 909\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
403; 1654\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-57-co2-5min-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2_10min}{%
\subsection{co2\_10min}\label{co2_10min}}

\emph{CO2 level at 10 minutes (ppm)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
3 (5.45 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
50\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
711\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
558.25; 918.25\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
408; 1619\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-58-co2-10min-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2_15min}{%
\subsection{co2\_15min}\label{co2_15min}}

\emph{CO2 level at 15 minutes (ppm)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
3 (5.45 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
49\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
716\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
564; 901.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
406; 1607\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-59-co2-15min-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2_20min}{%
\subsection{co2\_20min}\label{co2_20min}}

\emph{CO2 level at 20 minutes (ppm)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
4 (7.27 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
51\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
722\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
547.5; 918.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
405; 1611\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-60-co2-20min-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2_25min}{%
\subsection{co2\_25min}\label{co2_25min}}

\emph{CO2 level at 25 minutes (ppm)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
3 (5.45 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
51\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
746\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
561.25; 911\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
409; 1607\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-61-co2-25min-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{notes}{%
\subsection{notes}\label{notes}}

\emph{Notes:}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.35\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.35\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.35\columnwidth}\raggedleft
7 (12.73 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.35\columnwidth}\raggedleft
48\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.35\columnwidth}\raggedleft
``12th floors, Room 1202''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-62-notes-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "12th floors, Room 1202", "13th floor, room
  1301", "2 patients fed with intranasal canal.", "Bathroom of previous
  room. CO2 meter malfunctioned", "Cabin 15 (8th floor, new)", "Cabin 18
  (new location), room has 8' 10" x 9' 1" washroom", "Cabin 29 (8th
  floor), 9' 2" x 3' 6" washroom included", "Cabin 46, suspected COVIDZ
  but not confirmed, 9' 2" x 3' 2" washroom included.", "Children's OPD,
  highly dynamic flux of people, doctor's rooms partially sectioned off
  (top parts open)", "CO2 higher than usual value at same point. Room
  323.", "Continuous flux of people", "COVID Med OPS, 2nd building",
  "Flux of people", "Isolation ward 601 unit V", "Isolation ward 601
  unit VI", "Isolation ward 601, unit II Room 02", "Isolation ward 607",
  "Left side of 5th floor, other side recorded, room showed large
  variation in CO2", "Male ward @ 8th floor, another unit. Should we
  count number of ppl with oxygen masks who remove them", "Male ward @
  8th floor, unit 2", "Medicine OPD, Can't distinguish patients from
  visitors, constant flux", "Midpoint and door data not collected",
  "Midpoint and door data not taken", "Non rectangular room. All nasal
  cannula are high flow. Central AC.", "Partitioned room", "People left
  in the middle for lunch, recently turned on fan hence CO2 decrease,
  large continuous ventilation shafts 39.75 x 2.67 feet. Rectangular
  room, 6th floor `non acute child ward'", "Rectangular room",
  "Rectangular room with 6' x 5' 5" washroom", "Rectangular room with 7'
  2" x 6' 6" washroom", "Rectangular room with a 8' 10" x 6' washroom",
  "Rectangular room, `non acute female ward'", "Respiratory med OPD,
  line of patients outside at the door but not entering.", "Right side
  of 5th floor, room with large variation in CO2, other side recorded
  too", "Room 1110", "Room 1205", "Room 1208", "Room 1307. Rectangular
  room with a 9.75 x 6.5 feet washroom", "Room 1309. Rectangular with a
  9.75 x 6.5 feet washroom.", "Room 513, internal washroom of 6.75 by 6
  squared feet.", "Room 518", "Room 519", "Room was a post op, turned
  into COVID ICU. 6th floor.", "Small partitioned booth for Cardiology
  OPD. Ground floor open area, flux of people. Considered top of
  partitions as windows.", "Small room, closed door opened
  intermittently, some CO2 measurements couldn't be taken", "Sudden gust
  of wind in the middle of the experiment as it started raining", "Top
  left portion was blank, not homogeneous distribution of people",
  "Washroom of previous COVID ICU sampled (51\_MM\_R2), constant flux of
  people", "Washroom of previous room, opens up to 4 small stalls,
  biosampler on doorstep, constant flux of people".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{id}{%
\subsection{\_id}\label{id}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.34\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
55\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
77675222\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
76978218.5; 78831553.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
74480967; 80463536\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-63--id-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{submittime}{%
\subsection{submittime}\label{submittime}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.34\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
51\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.34\columnwidth}\raggedleft
``2020-12-16T16:01:10''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-64-submittime-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "2020-11-16T13:05:39", "2020-11-17T15:17:33",
  "2020-11-17T15:17:45", "2020-11-20T16:35:11", "2020-11-20T16:35:16",
  "2020-11-20T18:06:40", "2020-11-20T18:06:41", "2020-11-23T11:17:19",
  "2020-11-23T11:17:29", "2020-11-23T11:17:37", "2020-11-25T19:04:31",
  "2020-11-25T20:14:44", "2020-11-25T20:14:45", "2020-12-01T16:32:05",
  "2020-12-01T16:32:07", "2020-12-01T16:32:08", "2020-12-01T16:32:09",
  "2020-12-01T16:32:11", "2020-12-01T16:32:13", "2020-12-02T21:28:07",
  "2020-12-03T16:21:00", "2020-12-03T16:21:05", "2020-12-03T16:21:06",
  "2020-12-07T18:03:31", "2020-12-07T18:03:33", "2020-12-07T18:03:34",
  "2020-12-07T18:03:35", "2020-12-07T18:03:44", "2020-12-07T18:03:45",
  "2020-12-07T18:03:46", "2020-12-07T18:03:47", "2020-12-09T13:51:32",
  "2020-12-09T13:51:33", "2020-12-09T13:51:35", "2020-12-09T13:51:38",
  "2020-12-09T13:51:40", "2020-12-09T13:51:41", "2020-12-09T13:51:44",
  "2020-12-09T13:51:46", "2020-12-16T16:01:07", "2020-12-16T16:01:10",
  "2020-12-23T21:13:23", "2020-12-23T21:13:24", "2020-12-23T21:13:27",
  "2020-12-23T21:13:28", "2020-12-23T21:13:30", "2020-12-23T21:13:32",
  "2020-12-30T18:56:22", "2020-12-30T18:56:23", "2020-12-30T18:56:24",
  "2020-12-30T18:56:25".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{fixco2}{%
\subsection{fixco2}\label{fixco2}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.13\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 0\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.13\columnwidth}\raggedleft
0; 146\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-65-fixco2-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2startnew}{%
\subsection{co2startnew}\label{co2startnew}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
54\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
732\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
562.5; 911.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
421; 1586\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-66-co2startnew-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2_5minnew}{%
\subsection{co2\_5minnew}\label{co2_5minnew}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
2 (3.64 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
50\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
696\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
565; 886\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
403; 1509\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-67-co2-5minnew-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2_10minnew}{%
\subsection{co2\_10minnew}\label{co2_10minnew}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
3 (5.45 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
50\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
696.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
549; 868.75\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
408; 1474\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-68-co2-10minnew-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2_15minnew}{%
\subsection{co2\_15minnew}\label{co2_15minnew}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
3 (5.45 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
48\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
664.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
551.75; 869.25\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
406; 1462\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-69-co2-15minnew-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2_20minnew}{%
\subsection{co2\_20minnew}\label{co2_20minnew}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
4 (7.27 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
51\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
653\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
523; 867.5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
405; 1466\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-70-co2-20minnew-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2_25minnew}{%
\subsection{co2\_25minnew}\label{co2_25minnew}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
3 (5.45 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
51\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
718\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
533.5; 866\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
409; 1462\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-71-co2-25minnew-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2endnew}{%
\subsection{co2endnew}\label{co2endnew}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.21\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
1 (1.82 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
54\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
695\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
539.5; 855.75\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
404; 1459\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-72-co2endnew-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{co2average}{%
\subsection{co2average}\label{co2average}}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.24\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
55\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
715.71\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
545.71; 868.93\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.24\columnwidth}\raggedleft
409.57; 1488.29\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-73-co2average-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{washlocation}{%
\subsection{washlocation}\label{washlocation}}

\emph{Wash location}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
""\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-74-washlocation-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "", "-", "Lab".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{sampletype}{%
\subsection{sampletype}\label{sampletype}}

\emph{Sample type (Test/neg control)}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "TEST". The variable
  contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{collectionsite}{%
\subsection{collectionsite}\label{collectionsite}}

\emph{Collection site}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
5\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
``Open ward''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-76-collectionsite-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "Bathroom", "Cabin", "OPD", "Open ward",
  "Waiting Area".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{roomtype}{%
\subsection{roomtype}\label{roomtype}}

\emph{Room type}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.30\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
14\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.30\columnwidth}\raggedleft
``COVID general ward''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-77-roomtype-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "Cardiology booth", "COVID cabin", "COVID
  general ward", "COVID general ward A", "COVID general ward B", "COVID
  ICU", "COVID isolation ward", "COVID Sample collection", "COVID
  Triage", "COVID ward hallway", "Medicine OPD", "Non-COVID general
  ward", "Pediatric OPD", "Resp Medicine, doctor's cabin".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{result}{%
\subsection{result}\label{result}}

\emph{SARS-CoV-2 (Detected/undetected)}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
``Undetected''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-78-result-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "Detected", "Detected in 1 replicate",
  "Undetected".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{n1ctvalue}{%
\subsection{n1ctvalue}\label{n1ctvalue}}

\emph{N1-Ct value}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
16\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
``Undetermined''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-79-n1ctvalue-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "33.9", "34.4", "34.6/34.6", "35", "35.8",
  "35.9/34.9", "36.0/35.0", "36.1", "36.2", "36.3", "37", "37.1",
  "37.4", "38.1", "38.6/38.2", "Undetermined".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{n1quantityreaction}{%
\subsection{n1quantityreaction}\label{n1quantityreaction}}

\emph{N1-quantity/reaction}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
39 (70.91 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
16\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
29.7\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
2.6; 51.1\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
1; 147.6\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-80-n1quantityreaction-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{n1quantitysamplex10}{%
\subsection{n1quantitysamplex10}\label{n1quantitysamplex10}}

\emph{N1-quantity/sampleX10}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
39 (70.91 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
16\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
296.75\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
25.98; 511\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
9.54; 1476\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-81-n1quantitysamplex10-1.pdf}

\end{minipage}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{batchnumber}{%
\subsection{batchnumber}\label{batchnumber}}

\emph{Batch number}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
12\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
``12''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-82-batchnumber-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "10", "11", "12", "2", "3", "4", "5", "6",
  "7", "7 (re-run)", "8", "9".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{collectiondate}{%
\subsection{collectiondate}\label{collectiondate}}

\emph{Collection date}

\begin{minipage}{0.75 \textwidth}

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
14\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
""\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\end{minipage}
\begin{minipage}{0.25 \textwidth}

\includegraphics{COVID_aerosols_codebook_files/figure-latex/Var-83-collectiondate-1.pdf}

\end{minipage}

\begin{itemize}
\tightlist
\item
  Observed factor levels: "", "07/10/2020", "08/11/2020", "10/11/2020",
  "12/10/2020", "14/10/2020", "15/11/2020", "17/11/2020", "18/10/2020",
  "21/10/2020", "23/11/2020", "25/11/2020", "28/10/2020", "30/11/2020".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{rnadate}{%
\subsection{rnadate}\label{rnadate}}

\emph{RNA extraction Date}

\begin{itemize}
\tightlist
\item
  The variable only takes one value: "NA".
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

\hypertarget{comments}{%
\subsection{comments}\label{comments}}

\emph{Comments:}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "". The variable
  contains 0 \% missing observations.
\end{itemize}

\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}

Report generation information:

\begin{itemize}
\item
  Created by: Caitlin Hemlock (username: \texttt{caitlinhemlock}).
\item
  Report creation time: Wed Jan 06 2021 09:42:41
\item
  Report was run from directory: \texttt{/Users/caitlinhemlock}
\item
  dataMaid v1.4.0 {[}Pkg: 2019-12-10 from CRAN (R 4.0.2){]}
\item
  R version 4.0.2 (2020-06-22).
\item
  Platform: x86\_64-apple-darwin17.0 (64-bit)(macOS Catalina 10.15.6).
\item
  Function call:
  \texttt{dataMaid::makeDataReport(data\ =\ test,\ mode\ =\ c("summarize",\ "visualize",\ \ "check"),\ smartNum\ =\ FALSE,\ file\ =\ "\textasciitilde{}/Dropbox/COVID\ aerosols/codebook/COVID\_aerosols\_codebook.Rmd",\ \ replace\ =\ T,\ checks\ =\ list(character\ =\ "showAllFactorLevels",\ \ \ \ \ \ factor\ =\ "showAllFactorLevels",\ labelled\ =\ "showAllFactorLevels",\ \ \ \ \ \ haven\_labelled\ =\ "showAllFactorLevels",\ numeric\ =\ NULL,\ \ \ \ \ \ integer\ =\ NULL,\ logical\ =\ NULL,\ Date\ =\ NULL),\ listChecks\ =\ FALSE,\ \ maxProbVals\ =\ Inf,\ codebook\ =\ TRUE,\ reportTitle\ =\ "COVID\ Aerosols\ -\ Merged\ Data\ Codebook")}
\end{itemize}

\end{document}
