---
title: COVID AerosolTable One
author: Christopher Leboa 
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(dplyr)
library(ggplot2)
library(reshape2)
library(haven)
library(knitr)
library(tableone)

# Parameters
data_location <- "/Users/ChrisLeBoa/Dropbox/COVID_aerosols/clean data/2 25 21/mergeddata_22521.dta"

merged_data <- 
  read_dta(file = data_location) %>% 
  filter(ach < 40) %>%  ## removing sample point with really high ACH value 
  mutate(
    any_acon = if_else(numacon > 0 , "has air cond.", "no acon"),
    private =
      if_else(
      str_detect(
        hosp,
        "icddr|vercare|quare"), "private", "public"
      )
  )

#table(merged_data$private)
list <-
  c(
  "roomvol",
  "co2average", 
  "tempstart",
  "humiditystart",
  "numcovidstart",
  "numpeopleavg", 
  "numstaffstart",
  "popdensityavg", 
  "totfan", 
  "numacon", 
  "numdoortotal", 
  "doortofloorarea",
  "numdoorclosed", 
  "numwintotal", 
  "numwinclosed",
  "wintofloorarea",
  "ach",
  "ventrateavg"
  )

list_notnormal <- 
   c(
  "roomvol",
  "co2average", 
  #"tempstart",     #Histogram showed these two to be normally distributed 
  #"humiditystart",
  "numcovidstart",
  "numpeopleavg", 
  "numstaffstart",
  "popdensityavg", 
  "totfan", 
  "numacon", 
  "numdoortotal", 
  "doortofloorarea",
  "numdoorclosed", 
  "numwintotal", 
  "numwinclosed",
  "wintofloorarea",
  "ach",
  "ventrateavg"
  )


#===============================================================================


```

## Check normality of variables 
```{r}
histogram_fun = function(x) {
     ggplot(merged_data, aes_string(x = x) ) +
          geom_histogram() + 
          theme_bw() 
}

# histogram_fun(x = "roomvol") ## Testing fxn on one variable 

all_plots <- map(list, ~histogram_fun(.x))


all_plots
```
The histograms show that 

## Section 1
```{r}




# stratify by covidspace 

table_1_covidspace <- CreateTableOne(vars = list, strata = "covidspace", data = merged_data)
table_1_location <- CreateTableOne(vars = list, strata = "private", data = merged_data)
table_1_acon <- CreateTableOne(vars = list, strata = "any_acon", data = merged_data)


table_2_covidpos <- CreateTableOne(vars = list, strata = "result", data = merged_data)


table_2 <-  CreateTableOne(vars = list, data = merged_data)

tab_1_covidspace <- print(table_1_covidspace, nonnormal = list_notnormal, formatOptions = list(big.mark = ","))
tab_1_location <- print(table_1_location, nonnormal = list_notnormal, formatOptions = list(big.mark = ","))
tab_1_acon <- print(table_1_acon, nonnormal = list_notnormal, formatOptions = list(big.mark = ","))

tab_2_covidpos <- print(table_2_covidpos, nonnormal = list_notnormal, formatOptions = list(big.mark = ","))

# You can use kableone to print a tableone object in a markdown document but it will fail if you add in the notnormal thing like this kableone(tab2)

kableone(table_1_covidspace)
kableone(table_1_location)
kableone(table_1_acon)

summary(table_1_covidspace)



write.csv(tab_1_covidspace, file = "output/tab_1_covidspace.csv")
write.csv(tab_1_location, file = "output/tab_1_location.csv")
write.csv(tab_1_acon, file = "output/tab_1_acon.csv")

write.csv(tab_2_covidpos, file = "output/tab_2_covidpos.csv")

#end
```

